ab_tests.settings:
  type: config_object
  label: 'A/B Tests settings'
  mapping:
    ignore_config_export:
      type: boolean
      label: 'Ignore A/B Tests configuration during configuration export'
