ab_tests.variants.timeout_block:
  type: mapping
  mapping:
    id:
      type: string
    timeout:
      type: mapping
      mapping:
        min:
          type: string
        max:
          type: string
    available_variants:
      type: sequence
      sequence:
        type: ignore
