name: JavaScript Quality & Review

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Fast-fail quality check that runs on all pushes and PRs
  quality-check:
    name: JavaScript Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run JavaScript quality checks
        run: npm run js:check

  # Enhanced PR review with inline suggestions (only for PRs)
  pr-review:
    name: PR Review with Suggestions
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint with suggestions
        uses: CatChen/eslint-suggestion-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: '.'
          targets: 'js/ modules/*/js/'
          extensions: 'js'
          request-changes: true
          fail-check: false

      - name: Check Prettier formatting
        id: prettier-check
        run: |
          if ! npm run format:check; then
            echo "prettier-failed=true" >> $GITHUB_OUTPUT
            echo "## 🎨 Prettier Formatting Issues Found" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Some files are not properly formatted. Please run the following command to fix them:" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```bash' >> $GITHUB_STEP_SUMMARY
            echo 'npm run format:fix' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Or you can run this command to check which files need formatting:" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```bash' >> $GITHUB_STEP_SUMMARY
            echo 'npm run format:check' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Comment on PR for Prettier issues
        if: failure() && steps.prettier-check.outputs.prettier-failed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.payload.pull_request;

            const comment = `## 🎨 Prettier Formatting Issues

            Some JavaScript files in this PR are not properly formatted according to the project's Prettier configuration.

            ### How to fix:

            1. **Automatic fix** (recommended):
               \`\`\`bash
               npm run format:fix
               \`\`\`

            2. **Check formatting** (to see which files need fixing):
               \`\`\`bash
               npm run format:check
               \`\`\`

            3. **Manual fix**: You can also fix formatting issues manually by running Prettier on specific files:
               \`\`\`bash
               npx prettier --write path/to/file.js
               \`\`\`

            ### Configuration

            The formatting rules are defined in \`.prettierrc.json\` and follow Drupal JavaScript coding standards.

            Please format your code and push the changes to resolve this check. ✨`;

            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: comment
            });
