name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  testing:
    name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        drupal-core: ['10.4.x', '11.0.x']
        php-versions: ['8.3']
    steps:
      - name: Checkout Drupal core
        uses: actions/checkout@v4
        with:
          repository: drupal/drupal
          ref: ${{ matrix.drupal-core }}

      - name: Checkout module
        uses: actions/checkout@v4
        with:
          path: modules/ab_tests

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Drupal core dependencies
        run: |
          composer --no-interaction --no-progress --prefer-dist --optimize-autoloader install
#
#      - name: Install module dependencies
#        run: |
#          composer --no-interaction --no-progress require \
#            drupal/my-dependeny

      - name: Install Coder module
        run: |
          composer --dev --no-interaction --no-progress require \
            drupal/coder:^8

      - name: Check coding standards
        run: |
          ./vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,install modules/ab_tests

      - name: Run Tests
        run: |
          ./vendor/bin/phpunit -c core/phpunit.xml.dist modules/ab_tests
